################################### English language #####################################
[en]
languageName = "🇺🇸"
languageCode = "en-us"
contentDir = "content/english"
weight = 1


################################### French language #####################################
[pt-br]
languageName = "🇧🇷"
languageCode = "pt-br"
contentDir = "content/portugues"
weight = 2

