############# Portuguese navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Sobre"
url = "about/"
weight = 2

[[main]]
name = "O que eu faço"
url = "/pt-br/eu-faco/"
weight = 3

[[main]]
name = "Meu Portfolio"
url = "/pt-br/categories/portfolio/"
weight = 4

[[main]]
name = "Contato"
url = "contato/"
weight = 5
