############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "What I Do"
url = "i-do-that/"
weight = 3

[[main]]
name = "Portfolio"
url = "/categories/portfolio/"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 5

