baseURL: "https://llsaboya.com"
languageCode: "en-us"
title: "Breves Notas"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
theme: brevesnotas-novela
googleAnalytics: UA-174059-11

# module:
#   imports:
#     - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "https://twitter.com/llsaboya"
  github: "#"
  instagram: "https://www.instagram.com/llsaboya/"
  linkedin: "https://www.linkedin.com/in/llsaboya/"
  dribbble: "#"
  youtube: "https://www.youtube.com/channel/UCrUYEofsuTPiNSsq9S9W0HA"
taxonomies:
  author: authors
frontmatter:
  date: 
    - publishDate
    - :filename
    - date
    - :fileModTime
  publishDate: 
    - publishDate
    - :filename
    - date
    - :fileModTime