[Settings]

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "public"
  command = "hugo --minify --gc"

[build.environment]
  HUGO_VERSION = "0.110.0"
  NODE_VERSION = "19.6.0"
  NPM_VERSION = "9.4.0"
